version: '2'
services:

  # The Application
  app:
    image: laravel-app
    working_dir: /var/www
    container_name: laravel-example1-app
    volumes:
      - /var/www/inne/laravel-app-todo/:/var/www/
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    links:
      - database

  # The Web Server
  web:
    image: laravel-web
    working_dir: /var/www
    container_name: laravel-example1-web
    volumes_from:
      - app
    ports:
      - 8081:80

  # The Database
  database:
    image: mysql:5.7
    container_name: laravel-example1-db
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - 33600:3306

volumes:
  dbdata:
